repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-ast
    -   id: detect-private-key

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: python-no-eval

-   repo: https://github.com/asottile/pyupgrade
    rev: "v3.15.0"
    hooks:
    -   id: pyupgrade

-   repo: local
    hooks:
        - id: autoflake
          name: autoflake
          entry: autoflake
          language: python
          'types': [ python ]
          require_serial: true
          exclude: |
            (?x)(
                ^models_app/admin/__init__.py|
                ^models_app/models/__init__.py
            )

        - id: yesqa
          name: Strip unnecessary `# noqa`s
          description: Automatically remove unnecessary `# noqa` comments
          entry: yesqa
          language: python
          types: [ python ]

        - id: flake8
          args: [
            "--max-line-length", "120",
            "--extend-ignore", "E203",
            "--exclude",
            "models_app/admin/__init__.py, models_app/models/__init__.py, .git, .venv, __pycache__,
            models_app/migrations/*, settings, manage.py"
          ]
          name: flake8
          description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
          entry: flake8
          language: python
          types: [ python ]
          require_serial: true
          exclude: |
            (?x)(
                ^models_app/admin/__init__.py|
                ^models_app/models/__init__.py
            )

        - id: bandit
          name: bandit
          description: 'Bandit is a tool for finding common security issues in Python code'
          entry: bandit
          language: python
          language_version: python3
          types: [ python ]

        - id: black
          name: black
          description: "Black: The uncompromising Python code formatter"
          entry: black
          language: python
          minimum_pre_commit_version: 2.9.2
          require_serial: true
          types_or: [ python, pyi ]

        - id: isort
          name: isort (python)
          entry: isort
          language: python
          args: [ "--profile", "black"]
          types: [ python ]


        - id: mypy
          name: mypy
          description: ''
          entry: mypy
          language: python
          'types_or': [ python, pyi ]
          args: [ "--ignore-missing-imports", "--scripts-are-modules" ]
          require_serial: true
          exclude: /migrations/|models_app/admin/__init__.py
          additional_dependencies: [ ]
          minimum_pre_commit_version: '2.9.2'
