# Generated by Django 5.2.7 on 2025-12-18 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment_date",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата и время последнего обновления"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="state",
            field=models.CharField(
                choices=[
                    ("on_moderation", "On Moderation"),
                    ("approved", "Approved"),
                    ("on_delete", "On Delete"),
                    ("rejected", "Rejected"),
                ],
                default="on_moderation",
                max_length=63,
            ),
        ),
    ]
