# Generated by Django 5.2.7 on 2025-12-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0002_remove_comment_comment_date_comment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="title",
            field=models.CharField(
                blank=True, max_length=511, null=True, verbose_name="Название"
            ),
        ),
    ]
