# Generated by Django 5.2.7 on 2025-12-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0003_photo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="state",
            field=models.CharField(
                choices=[
                    ("on_moderation", "On Moderation"),
                    ("approved", "Approved"),
                    ("on_delete", "On Delete"),
                    ("rejected", "Rejected"),
                ],
                default="on_moderation",
                max_length=63,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название"
            ),
        ),
    ]
