# Generated by Django 5.2.7 on 2026-02-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0004_alter_photo_state_alter_photo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Фото профиля"
            ),
        ),
    ]
