# Generated by Django 5.2.7 on 2026-02-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0005_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Фото профиля"
            ),
        ),
    ]
