# Generated by Django 5.2.7 on 2026-02-18 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0006_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="models_app.comment",
                verbose_name="Родительский комментарий",
            ),
        ),
    ]
