# Generated by Django 5.2.7 on 2026-02-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0007_comment_parent_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="publication_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата и время публикации"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
