# Generated by Django 5.2.7 on 2026-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0008_alter_photo_publication_date_alter_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="previous_image",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Предыдущее фото"
            ),
        ),
    ]
