# Generated by Django 5.2.7 on 2026-06-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0009_photo_previous_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_pic",
            new_name="avatar",
        ),
    ]
