# Generated by Django 5.2.7 on 2026-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0010_rename_profile_pic_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фото профиля"
            ),
        ),
    ]
