from config.settings.django import env

CELERY_BROKER_URL = env("CELERY_BROKER_URL", cast=str)
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", cast=str)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
